# Generated by Django 6.0 on 2025-12-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_cursosrealizados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fotoproducto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Foto del Producto'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Subir Certificado (PDF o Imagen)'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/', verbose_name='Archivo del Reconocimiento'),
        ),
    ]
