# Generated by Django 6.0 on 2025-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_datospersonales_perfilactivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUnificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURSOS', 'Certificados de Cursos'), ('RECONOCIMIENTOS', 'Reconocimientos y Premios')], max_length=20, unique=True, verbose_name='Categoría del Reporte')),
                ('archivo_pdf', models.FileField(upload_to='reportes_unificados/', verbose_name='Archivo PDF Unificado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': '8. Reporte Unificado',
                'verbose_name_plural': '8. Reportes Unificados',
            },
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Subir Certificado'),
        ),
    ]
