# Generated by Django 6.0 on 2025-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_reporteunificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='url_certificado_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link del Certificado'),
        ),
    ]
