# Generated by Django 6.0 on 2025-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_experiencialaboral_url_certificado_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosrealizados',
            name='url_certificado_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace al Certificado (URL)'),
        ),
    ]
