# Generated by Django 6.0 on 2025-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_cursosrealizados_url_certificado_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimientos',
            name='url_certificado_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo al Reconocimiento (URL)'),
        ),
    ]
