# Generated by Django 6.0 on 2025-12-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_reconocimientos_url_certificado_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='url_certificado_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link del Certificado'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='url_certificado_externo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link del Certificado'),
        ),
    ]
