# Generated by Django 6.0 on 2026-01-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_cursosrealizados_url_certificado_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=250, verbose_name='Cargo Desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(max_length=250, verbose_name='Descripción de Funciones'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Web de la Empresa'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
    ]
