# Generated by Django 6.0 on 2026-01-25 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_cursosrealizados_descripcioncurso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteUnificado',
        ),
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'ordering': ['-fechainicio'], 'verbose_name': 'Curso', 'verbose_name_plural': '3. Cursos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fechainiciogestion'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'ordering': ['-fechaproducto'], 'verbose_name': 'Producto Laboral', 'verbose_name_plural': '5. Productos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'ordering': ['-fechareconocimiento'], 'verbose_name': 'Reconocimiento', 'verbose_name_plural': '6. Reconocimientos'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fechapublicacion'], 'verbose_name': 'Artículo de Garage', 'verbose_name_plural': '7. Venta de Garage'},
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación'),
        ),
    ]
