# Generated by Django 6.0 on 2026-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_delete_reporteunificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='ver_cursos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Cursos en la Web?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ver_experiencia',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Experiencia en la Web?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ver_garage',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Garage en la Web?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ver_productos_academicos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Prod. Académicos en la Web?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ver_productos_laborales',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Prod. Laborales en la Web?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ver_reconocimientos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Reconocimientos en la Web?'),
        ),
    ]
